version: '3.8'
services:
  web:
    #image: ghcr.io/miiyakii/merge-web-server:latest
    build: .
    
    ports:
      - "5001:5001"
    environment:
      - API_URL= # 留空即可，前后端同容器使用相对路径
    # volumes:
    #   - ./证书名字.docx:/app/证书名字.docx # 如需挂载证书模板
    restart: unless-stopped
    networks:
      - caddy_net
    hostname: merge-web-server

networks:
  caddy_net:
    driver: bridge
